#!/bin/bash
# $Id: beautify,v 1.2 2011/09/19 10:16:33 sfws Exp $
#
# will suppress empty and comment lines, useful for these over-commented sample config files someone has been into

REGEX='/^$/d;/^#/!p;'

if [ $# -eq 0 ]; then
	/bin/sed -n ${REGEX}
elif [ -n "$(echo $1 | sed -n '/-[h?]/p')" ]; then
	echo Usage: ${0##/*/} [filename] >&2
	echo '      ' cat filename \| ${0##/*/} >&2
	exit 1
elif [ -e $1 ]; then
	/bin/sed -n ${REGEX} $1
else
	echo No such file: $1 >&2
	exit 1
fi
