#! /bin/bash
# Wed Feb 12 10:50:50 UTC 2020; HH-RIPE; Henrik Harms
# Sichert die Kernel IP-Sets nach Namen getrennt
# $Id: ipset_saver,v 1.3 2023/12/19 10:09:11 hippie Exp $
# vim: set nohlsearch ts=4 sw=4 :

IPSET='/sbin/ipset'
BASE='/etc/ipsets'
SUFFIX='conf'

mkdir -p ${BASE}

for SET in $( ${IPSET} list -t | grep "Name: " | cut -d ' ' -f2); do
	${IPSET} save ${SET} > ${BASE}/${SET}.${SUFFIX}
done
